//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texture.Win64.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Texture.Win64.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   layer 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _button_layer1_Text {
            get {
                return ResourceManager.GetString("_button_layer1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   layer 2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _button_layer2_Text {
            get {
                return ResourceManager.GetString("_button_layer2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   write に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _button_write_Text {
            get {
                return ResourceManager.GetString("_button_write_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _checkBox_layer2_Text {
            get {
                return ResourceManager.GetString("_checkBox_layer2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   expand mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _checkBox_mode_expand_Text {
            get {
                return ResourceManager.GetString("_checkBox_mode_expand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _checkBox_mode_line_Text {
            get {
                return ResourceManager.GetString("_checkBox_mode_line_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rock mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _checkBox_mode_rock_Text {
            get {
                return ResourceManager.GetString("_checkBox_mode_rock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _groupBox_layer_Text {
            get {
                return ResourceManager.GetString("_groupBox_layer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _groupBox_line_Text {
            get {
                return ResourceManager.GetString("_groupBox_line_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   modify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _groupBox_modify_Text {
            get {
                return ResourceManager.GetString("_groupBox_modify_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _groupBox_rect_Text {
            get {
                return ResourceManager.GetString("_groupBox_rect_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   view に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _groupBox_view_Text {
            get {
                return ResourceManager.GetString("_groupBox_view_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   accent: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_accent_Text {
            get {
                return ResourceManager.GetString("_label_accent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   satur. adjust: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_adjust_saturation_Text {
            get {
                return ResourceManager.GetString("_label_adjust_saturation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   value adjust: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_adjust_value_Text {
            get {
                return ResourceManager.GetString("_label_adjust_value_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   alpha: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_alpha_Text {
            get {
                return ResourceManager.GetString("_label_alpha_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   crop: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_crop_Text {
            get {
                return ResourceManager.GetString("_label_crop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   height: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_height_Text {
            get {
                return ResourceManager.GetString("_label_height_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   language: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_language_Text {
            get {
                return ResourceManager.GetString("_label_language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   transparency: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_pen_alpha_Text {
            get {
                return ResourceManager.GetString("_label_pen_alpha_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   thickness: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_pen_width_Text {
            get {
                return ResourceManager.GetString("_label_pen_width_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   piece_count: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_piece_count_Text {
            get {
                return ResourceManager.GetString("_label_piece_count_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   primary: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_primary_Text {
            get {
                return ResourceManager.GetString("_label_primary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hue range: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_range_hue_Text {
            get {
                return ResourceManager.GetString("_label_range_hue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   satur. range: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_range_saturation_Text {
            get {
                return ResourceManager.GetString("_label_range_saturation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   value range: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_range_value_Text {
            get {
                return ResourceManager.GetString("_label_range_value_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   secondary: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_secondary_Text {
            get {
                return ResourceManager.GetString("_label_secondary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   swing: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_swing_Text {
            get {
                return ResourceManager.GetString("_label_swing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   width: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _label_width_Text {
            get {
                return ResourceManager.GetString("_label_width_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture Generation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_Text {
            get {
                return ResourceManager.GetString("FormMain_Text", resourceCulture);
            }
        }
    }
}
